# Generated by Django 5.0.2 on 2024-02-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='adress',
            new_name='address',
        ),
    ]
