# Generated by Django 5.0.2 on 2024-04-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_productrating_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_customers', to='main.customer'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
