# Generated by Django 5.0.2 on 2024-08-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='endereco_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='endereco_origem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='produtos',
            field=models.ManyToManyField(to='main.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Esperando pagamento', 'Esperando pagamento'), ('Pagamento confirmado', 'Pagamento confirmado'), ('Nota fiscal emitida', 'Nota fiscal emitida'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Devolvido', 'Devolvido'), ('Cancelado', 'Cancelado')], default='Esperando pagamento', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
