# Generated by Django 5.0.2 on 2024-08-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order_endereco_destino_order_endereco_origem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
