# Generated by Django 5.0.2 on 2024-08-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='default_address',
            new_name='favorite_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='endereco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_destination', to='main.customeraddress'),
        ),
    ]
