# Generated by Django 5.0.2 on 2024-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_customeraddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ddd_mobile',
            field=models.PositiveSmallIntegerField(default='021'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
