# Generated by Django 5.0.2 on 2024-08-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_useraddress_vendoraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='addresses',
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_addresses', to='main.vendor'),
        ),
    ]
