# Generated by Django 5.0.2 on 2024-08-06 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_customer_addresses_remove_vendor_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='favorite_address',
            field=models.BooleanField(default=False),
        ),
    ]
