# Generated by Django 5.0.2 on 2024-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_order_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='frete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
